### ISSUE TITLE
ADE20k preprocessing

### ISSUE THREAD

**Issue by db-scch** [matejgrcic/DenseHybrid#1]
The code expects a very specific directory structure for the negatives dataset, so if using the ADE20k dataset certain preparatory steps are necessary.
It would also make sense for me to filter the dataset in a way, so that only objects/segments that are plausible to appear in the given scenario (e.g. urban scenes) are inserted into the images.
This leads me to the question: Did you use a script to preprocess/filter the ADE dataset in any way, and if so, could you provide it?

Thanks!

Awesome work btw!

**Comment by matejgrcic** [comment]
Hi, thanks for your interest in our work.

We have used the ADEChallengeData2016 version of ADE20k. You can download it by running `wget http://data.csail.mit.edu/places/ADEchallenge/ADEChallengeData2016.zip`. The unzipped content should have the appropriate directory structure.

From an open-set recognition perspective, the negative content used during the training (KUC) should not be equal to anomalies used for testing (UUC). Otherwise, the performance estimate would be overoptimistic. You can find more about KUCs and UUCs [here](https://arxiv.org/pdf/1811.08581.pdf).

**Comment by db-scch** [comment]
That is very helpful, thank you so much!
